### ISSUE TITLE
need 'display_name' to display field 'name'

### ISSUE THREAD

**Issue by donny26utama** [LaravelDaily/laravel-permissions-ui#4]

**Comment by krekas** [comment]
@donny26utama what are you talkint about?

**Comment by donny26utama** [comment]
maybe I post this issue in spatie/laravel-permission
but in UI we need more readable 
![image](https://user-images.githubusercontent.com/13846150/196415595-0d574ecf-8cd6-4c3c-8551-377d1758c967.png)
maybe we need some text different name to permission. and grouping name too (in the picture 'User')

**Comment by krekas** [comment]
Sorry, still don't understand what is the problem

**Comment by donny26utama** [comment]
I think this is a feature request,
![image](https://user-images.githubusercontent.com/13846150/196423611-89973508-21d0-477d-b345-3c6ca59a8156.png)
rather than show the field 'name', sometimes we need text to explain that permission.
for example, I have a page to manage Customers. this page only can access by a user/role that has permission 'manage_customer' on the page to assign this permission, I think rather than use the field 'name' on the checkbox label, we can use the 'display_name' field as a label. I hope we can do like this:
```
<label for="{{$permission->name}}">
    <input type="checkbox" name="permission[]" value="{{$permissoin->name}}"> {{$permission->display_name}}
</label>
```
if we use case 'manage_customer'
```
<label for="manage_customer">
    <input type="checkbox" name="permissions[]" value="manage_customer}"> Can Manage Customer
</label>
```

**Comment by krekas** [comment]
It's a custom thing and I think you should do it yourself, because spatie/laravel-permission doesn't have field for description or some other extra data. Either by extending spatie package or doing from scratch

**Comment by donny26utama** [comment]
yeah, I understand. I just want to share something in my head when you want to make UI manage RBAC. We hope Spatie can handle this case in their way. Thanks for your comments. Nice job.

**Comment by donnyatspe** [comment]
I see on your youtube video comment, someone asking about same with me. "nice_name" for non dev user.
